"use client";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// Custom theme for blue/white sleek look (optional, but good practice)
const theme = extendTheme({
  colors: {
    brand: {
      500: "#1976D2", // A nice Material Blue
      600: "#1565C0",
    },
  },
  styles: {
    global: {
      "html, body": {
        fontFamily: "Inter, sans-serif",
      },
    },
  },
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
